// Generated by scripts/validate-file-capabilities.mjs. Do not edit by hand.

export type ParseRuntime = "browser" | "hybrid" | "native";

export interface FileCapability {
  extension: FileExtension;
  displayLabel: string;
  parserId: string;
  mimeHints: readonly string[];
  maxFileSizeBytes: number;
  ocr: { supported: false } | { supported: true; parserId: string };
  parseRuntime: ParseRuntime;
  defaultEnabled: boolean;
}

export const SUPPORTED_FILE_CAPABILITIES = [
  {
    extension: "txt",
    displayLabel: "Text",
    parserId: "txt-utf8",
    mimeHints: ["text/plain"],
    maxFileSizeBytes: 52428800,
    ocr: { supported: false },
    parseRuntime: "browser",
    defaultEnabled: true,
  },
  {
    extension: "pdf",
    displayLabel: "PDF",
    parserId: "pdf-text",
    mimeHints: ["application/pdf"],
    maxFileSizeBytes: 52428800,
    ocr: { supported: true, parserId: "pdf-ocr" },
    parseRuntime: "hybrid",
    defaultEnabled: true,
  },
  {
    extension: "docx",
    displayLabel: "Word document",
    parserId: "docx-mammoth",
    mimeHints: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    maxFileSizeBytes: 52428800,
    ocr: { supported: false },
    parseRuntime: "browser",
    defaultEnabled: true,
  },
  {
    extension: "doc",
    displayLabel: "Legacy Word document",
    parserId: "doc-antiword",
    mimeHints: ["application/msword"],
    maxFileSizeBytes: 52428800,
    ocr: { supported: false },
    parseRuntime: "native",
    defaultEnabled: true,
  },
] as const satisfies readonly FileCapability[];

export const SUPPORTED_FILE_EXTENSIONS = ["txt", "pdf", "docx", "doc"] as const;

export type FileExtension = (typeof SUPPORTED_FILE_EXTENSIONS)[number];

export function isSupportedFileExtension(value: string): value is FileExtension {
  return (SUPPORTED_FILE_EXTENSIONS as readonly string[]).includes(value.toLowerCase());
}

function normalizeExtension(value: string): string {
  const trimmed = value.trim().toLowerCase();
  return trimmed.startsWith(".") ? trimmed.slice(1) : trimmed;
}

export function getFileCapability(value: string): FileCapability | null {
  const extension = normalizeExtension(value);
  return SUPPORTED_FILE_CAPABILITIES.find((capability) => capability.defaultEnabled && capability.extension === extension) ?? null;
}

export const FILE_EXTENSION_FILTER_OPTIONS = [
  { value: "txt", label: "Text" },
  { value: "pdf", label: "PDF" },
  { value: "docx", label: "Word document" },
  { value: "doc", label: "Legacy Word document" },
] as const;
