// Generated by scripts/validate-file-capabilities.mjs. Do not edit by hand.

export const GENERATED_FILE_EXTENSIONS = ["txt", "pdf", "docx", "doc"] as const;

export const FILE_EXTENSION_SQL_LIST = "'txt', 'pdf', 'docx', 'doc'";

export const FILE_EXTENSION_CHECK_SQL = "file_extension IN ('txt', 'pdf', 'docx', 'doc')";

export const FILE_EXTENSION_DELETE_UNSUPPORTED_SQL =
  "file_extension NOT IN ('txt', 'pdf', 'docx', 'doc')";
