// Generated by scripts/validate-file-capabilities.mjs. Do not edit by hand.

use std::path::Path;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ParseRuntime {
    Browser,
    Hybrid,
    Native,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FileCapability {
    pub extension: &'static str,
    pub display_label: &'static str,
    pub parser_id: &'static str,
    pub mime_hints: &'static [&'static str],
    pub max_file_size_bytes: u64,
    pub ocr_parser_id: Option<&'static str>,
    pub parse_runtime: ParseRuntime,
    pub default_enabled: bool,
}

pub const SUPPORTED_FILE_CAPABILITIES: &[FileCapability] = &[
    FileCapability {
        extension: "txt",
        display_label: "Text",
        parser_id: "txt-utf8",
        mime_hints: &["text/plain"],
        max_file_size_bytes: 52_428_800,
        ocr_parser_id: None,
        parse_runtime: ParseRuntime::Browser,
        default_enabled: true,
    },
    FileCapability {
        extension: "pdf",
        display_label: "PDF",
        parser_id: "pdf-text",
        mime_hints: &["application/pdf"],
        max_file_size_bytes: 52_428_800,
        ocr_parser_id: Some("pdf-ocr"),
        parse_runtime: ParseRuntime::Hybrid,
        default_enabled: true,
    },
    FileCapability {
        extension: "docx",
        display_label: "Word document",
        parser_id: "docx-mammoth",
        mime_hints: &["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
        max_file_size_bytes: 52_428_800,
        ocr_parser_id: None,
        parse_runtime: ParseRuntime::Browser,
        default_enabled: true,
    },
    FileCapability {
        extension: "doc",
        display_label: "Legacy Word document",
        parser_id: "doc-antiword",
        mime_hints: &["application/msword"],
        max_file_size_bytes: 52_428_800,
        ocr_parser_id: None,
        parse_runtime: ParseRuntime::Native,
        default_enabled: true,
    },
];

pub const SUPPORTED_FILE_EXTENSIONS: &[&str] = &["txt", "pdf", "docx", "doc"];

pub fn supported_extension(path: &Path) -> Option<&'static str> {
    let extension = path.extension()?.to_str()?.to_ascii_lowercase();
    SUPPORTED_FILE_EXTENSIONS
        .iter()
        .copied()
        .find(|supported| *supported == extension)
}
